### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by akien-mga** [marcosbitetti/godot_balloon_text#2]
Your asset submission on the Asset Library says that the license is MIT: https://godotengine.org/asset-library/asset/edit/545

But there is no LICENSE file in the repository to confirm that, and instead there is a CC-BY 4.0 International header in https://github.com/marcosbitetti/godot_balloon_text/blob/master/addons/balloon/balloon.gd

**Comment by marcosbitetti** [comment]
The two licences are permissives. Godot Library Repo at publish moment having poor support for artistc licencing.
